### ISSUE TITLE
Let title be optional

### ISSUE THREAD

**Issue by elliot-nelson** [hamxabaig/new-github-pull-request-url#1]
If you use the quick pull URL and don't specify a title, GitHub will pre-populate the last commit message in the branch.  This can be a useful default if you don't have a title to insert for the user.

If `title` is not provided, it would be nice if the package omitted it from the URL instead of erroring out, allowing GitHub to use its default title.

**Comment by hamxabaig** [comment]
@elliot-nelson makes sense, You want to give it a try and PR here? Otherwise i'll check it out on weekend.
